package br.com.mca.listview;

import java.util.ArrayList;
import java.util.List;

import br.com.mca.listview.adapter.MyAdapter;

import android.app.Activity;
import android.os.Bundle;
import android.view.View;
import android.widget.AdapterView;
import android.widget.AdapterView.OnItemClickListener;
import android.widget.ListView;
import android.widget.Toast;

/**
 * @author luis82fernandez
 */
public class ListViewActivity extends Activity {

	private ListView mListView;
	private OnItemClickListener mOnItemClickListener;

	private List<String> mList;
	
	@Override
	protected void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
		this.setContentView(R.layout.screen_listview);

		mListView = (ListView) findViewById(R.screenListView.listView);
		mOnItemClickListener = new OnItemClickListener() {

			@Override
			public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
				// Exibe um Toast com o texto do ítem clicado
				Toast.makeText(getApplicationContext(), mList.get(position), Toast.LENGTH_LONG).show();
			}
		};
	}

	@Override
	protected void onPostCreate(Bundle savedInstanceState) {
		super.onPostCreate(savedInstanceState);

		this.ensureUI();
	}

	private void ensureUI() {
		// Carrega os dados
		mList = this.loadData();
		
		// Instância o Adapter passando o ArrayList dos dados
		MyAdapter adapter = new MyAdapter(getApplicationContext(), mList);
		
		// Configura o Adapter na ListView
		mListView.setAdapter(adapter);
		
		// Configura o listener que captura o clique em um ítem da lista
		mListView.setOnItemClickListener(mOnItemClickListener);
	}
	
	/**
	 * Dados retirados do site http://goo.gl/Sfahp IFFHS
	 * @return
	 */
	private List<String> loadData() {
		List<String> list = new ArrayList<String>();
		list.add("FC Barcelona");
		list.add("CD Universidad de Chile Santiago");
		list.add("CA Boca Juniors Buenos Aires");
		list.add("Real Madrid CF");
		list.add("Club Atlético de Madrid");
		list.add("Chelsea FC London");
		list.add("FC Bayern München");
		list.add("SC Corinthians Paulista São Paulo");
		list.add("Athletic Club de Bilbao");
		list.add("CA Vélez Sarsfield");
		list.add("Club Libertad Asunción");
		list.add("FC Twente Enschede");
		list.add("Santos FC");
		list.add("FC Basel");
		list.add("Fluminense FC Rio de Janeiro");
		list.add("SSC Napoli");
		list.add("CR Vasco da Gama Rio de Janeiro");
		list.add("PSV Eindhoven");
		list.add("Manchester City FC");
		list.add("Glasgow Celtic FC");
		list.add("Milan AC");
		list.add("PAE Olympiakos SFP Pireas");
		list.add("Valencia CF");
		list.add("Hannoverscher SV 1896");
		list.add("Sociedad Deportivo Quito");
		list.add("RSC Anderlecht");
		list.add("Sporting Clube de Portugal Lisboa");
		list.add("FC Internazionale Milano");
		list.add("BV Borussia Dortmund");
		list.add("Olympique Lyonnais");
		list.add("FC Schalke 04");
		list.add("Manchester United FC");
		list.add("Club de Futbol Monterrey");
		list.add("Juventus FC Torino");
		list.add("Olympique de Marseille");
		list.add("SC Internacional Porto Alegre");
		list.add("FK Metalist Charkiv");
		list.add("SS Lazio Roma");
		list.add("SK Viktoria Plze?");
		list.add("Arsenal FC London");
		list.add("Club Sport Emelec Guayaquil");
		list.add("Espérance Sportive de Tunis");
		list.add("Paris Saint-Germain FC");
		list.add("Liverpool FC");
		list.add("FC København");
		list.add("Udinese Calcio");
		list.add("Club Santos Laguna de Torreon");
		list.add("NK Maribor (piv. Lazne)");
		list.add("Ulsan Hyundai Horangi FC");
		list.add("Tottenham Hotspur FC");
		list.add("FBC Olimpia Asunción");
		list.add("Arsenal FC Sarandí");
		list.add("PAOK Thessaloniki");
		list.add("AZ Alkmaar");
		list.add("FC Shakhtar Donetsk");
		list.add("CD Universidad Católica Santiago");
		list.add("Fenerbahçe SK ?stanbul");
		list.add("FC Steaua Bucure?ti");
		list.add("CFR 1907 Cluj");
		list.add("NK Dinamo Zagreb");
		list.add("APOEL Lefkosia");
		list.add("CB Jeonbuk Hyundai Motors");
		list.add("Club Brugge KV");
		list.add("FC Dinamo Kyiv");
		list.add("Cerro Porteño FBC Asunción");
		list.add("Al-Hilal Omdurman");
		list.add("Grêmio Foot-Ball Porto-Alegrense");
		list.add("CA Lanús");
		list.add("Lille Olympique Sporting Club");
		list.add("Club Deportivo Unión Española Santiago");
		list.add("KRC Genk");
		list.add("FC Anzhi Makhachkala");
		list.add("Sport Lisboa e Benfica");
		list.add("AEL Lemesos");
		list.add("Royal Standard de Liège");
		list.add("AFC Rapid Bucure?ti");
		list.add("FC BATE Barysau");
		list.add("CR Flamengo Rio de Janeiro");
		list.add("FC Girondins de Bordeaux");
		list.add("AFC Ajax Amsterdam");
		list.add("São Paulo FC");
		list.add("Kashiwa Reysol");
		list.add("Rosenborg BK Trondheim");
		list.add("KP Legia Warszawa");
		list.add("Sporting Club Vaslui");
		list.add("CD Cruz Azul Ciudad de México");
		list.add("Club Nacional de Football Montevideo");
		list.add("Málaga CF");
		list.add("FC Pohang Steelers");
		list.add("Sporting Clube de Braga");
		list.add("AC Sparta Praha");
		list.add("Liga Deportiva Universitaria de Quito");
		list.add("UD Levante");
		list.add("CA Independiente Avellaneda");
		list.add("Esteghlal FC Tehran");
		list.add("FK Rubin Kazan");
		list.add("TSV Bayer 04 Leverkusen");
		list.add("Barcelona Sporting Club Guayaquil");
		list.add("CDC Atlético Nacional Medellín");
		list.add("CA Tigre");
		list.add("Hapoel Tel-Aviv FC");
		list.add("VfL Borussia Mönchengladbach");
		list.add("Al-Merreikh Omdurman");
		list.add("Al-Hilal FC Riyadh");
		list.add("FC Zenit St. Petersburg");
		list.add("FK Partizan Beograd");
		list.add("FC do Porto");
		list.add("Panathinaikos AO Athens");
		list.add("Montpellier Hérault Sports Club");
		list.add("Coritiba FC");
		list.add("FC Red Bull Salzburg");
		list.add("SE Palmeiras São Paulo");
		list.add("Bursaspor K Bursa");
		list.add("Be?ikta? JK ?stanbul");
		list.add("Al-Ittihad Club Jeddah");
		list.add("Newcastle United FC");
		list.add("CPD Junior Barranquilla");
		list.add("Tokyo FC");
		list.add("Everton FC");
		list.add("Chelsea FC Berekum");
		list.add("Stade Rennais FC");
		list.add("Universitario de Nuevo León Monterrey");
		list.add("FK Crvena zvezda Beograd");
		list.add("CA Colón de Santa Fe");
		list.add("LDU de Loja");
		list.add("Millonarios FC Bogotá");
		list.add("FM Sepahan Isfahan");
		list.add("Stoke City FC");
		list.add("Al-Ahly Cairo");
		list.add("AC Horsens");
		list.add("FC Sheriff Tiraspol");
		list.add("Club Juan Aurich de Chiclayo");
		list.add("CA Mineiro Belo Horizonte");
		list.add("VfB Stuttgart");
		list.add("Club Bolívar La Paz");
		list.add("Chonburi FC");
		list.add("SC Lokeren");
		list.add("Nagoya Grampus");
		list.add("Trabzonspor K Trabzon");
		list.add("Sunshine Stars FC Akure");
		list.add("CCD Tolima Ibague");
		list.add("Racing Club Avellaneda");
		list.add("Kelantan FA Kota Bahru");
		list.add("Defensor Sporting Club Montevideo");
		list.add("Wydad AC Casablanca");
		list.add("Eskisehirspor");
		list.add("Al-Ittifaq Dammam");
		list.add("FC Slovan Liberec");
		list.add("Seattle Sounders FC");
		list.add("FC Lokomotiv Moscow");
		list.add("Videoton FC Székesféhervár");
		list.add("Molde FK");
		list.add("Club Sport Herediano");
		list.add("Santa Fe CD Bogotá");
		list.add("PFC CSKA Moscow");
		list.add("Grupo Desportivo Interclube Luanda");
		list.add("FC Dacia Chi?in?u");
		list.add("Hapoel Ironi Kiryat Shmona FC");
		list.add("Al-Jazeera Abu Dhabi");
		list.add("KAA Gent");
		list.add("MAS Fès");
		list.add("Fulham FC");
		list.add("Galatasaray SK ?stanbul");
		list.add("FK Ekranas Panev??ys");
		list.add("PEA Buriram United FC");
		list.add("Al-Ahli SC Jeddah");
		list.add("CS Marítimo Funchal");
		list.add("Tromsø IL");
		list.add("FC Dinamo Bucure?ti");
		list.add("AS Roma");
		list.add("Club Africain Tunis");
		list.add("Real Club Deportivo Mallorca");
		list.add("Suwon Samsung Blue-Wings FC");
		list.add("CD Godoy Cruz Antonio Tomba Mendoza");
		list.add("Atromitos Athens");
		list.add("BSC Young Boys Bern");
		list.add("FC Asteras Tripolis");
		list.add("Zamalek SC Cairo");
		list.add("Linfield FAC");
		list.add("SK Liep?jas Metalurgs");
		list.add("FC Dnipr Dnipropetrovsk");
		list.add("Ajaccio AC");
		list.add("SC Heerenveen");
		list.add("FC Metalurh Donetsk");
		list.add("Seongnam Ilhwa Chunma FC");
		list.add("Liverpool FC Montevideo");
		list.add("Adelaide United FC");
		list.add("FC Dila Gori");
		list.add("FK Bunyodkor Tashkent");
		list.add("HJK Helsinki");
		list.add("CD Isidro Metapán");
		list.add("Helsingborg IF");
		list.add("Al-Kuwait SC Kaifan");
		list.add("CA Peñarol Montevideo");
		list.add("Djoliba AC Bamako");
		list.add("FK Renova Dzepci?te Tetova");
		list.add("Heart of Midlothian FC Edinburgh");
		list.add("FC Levadia Tallínn");
		list.add("Dynamos FC Harare");
		list.add("Nacional FBC Asunción");
		list.add("CD Cobreloa Calama");
		list.add("KKS Lech Pozna?");
		list.add("Sporting Cristal Lima");
		list.add("Guaraní FC Asunción");
		list.add("KV Kortrijk");
		list.add("FC Parma");
		list.add("AC Siena");
		list.add("Al-Qadsia SC Kuwait-City");
		list.add("CA Newell's Old Boys Rosario");
		list.add("Debreceni VSC");
		list.add("SBV Vitesse Arnhem");
		list.add("Botafogo FR Rio de Janeiro");
		list.add("Club Atlético Monarcas Morelia");
		list.add("Liga Deportiva Alajuelense Alajuela");
		list.add("Wis?a Kraków SA");
		list.add("Envigado FC");
		list.add("FC Dinamo Moscow");
		list.add("CD Iquique");
		list.add("SK Tiranë");
		list.add("Club The Strongest La Paz");
		list.add("FC Luzern");
		list.add("Anorthosis Ammochostos");
		list.add("FC Arsenal Kyiv");
		list.add("FK Gomel");
		list.add("Club Estudiantes de La Plata");
		list.add("Esporte Clube Bahia Salvador");
		list.add("Bologna Calcio");
		list.add("ASO Chlef");
		list.add("FC Seoul");
		list.add("Kalmar FF");
		list.add("FK Vojvodina Novi Sad");
		list.add("Club El Nacional Quito");
		list.add("FC Nordsjælland (Farum)");
		list.add("Los Angeles Galaxy");
		list.add("SK SIGMA Olomouc");
		list.add("Arbil Sport Club");
		list.add("Pakhtakor FK Tashkent");
		list.add("CSD Xelajú MC");
		list.add("AIK Solna");
		list.add("AA Argentinos Juniors Buenos Aires");
		list.add("CSD Municipal Guatemala City");
		list.add("CA All Boys");
		list.add("Kuopio Palloseura");
		list.add("Guangzhou Evergrande FC");
		list.add("Club Deportivo Guadalajara");
		list.add("Muang Thong United FC");
		list.add("St. Patrick's Athletic FC");
		list.add("FC Metalurgist Rustavi");
		list.add("Valenciennes AFC");
		list.add("AS de Saint-Etienne");
		list.add("Club Atletico Belgrano Cordoba");
		list.add("AC Chievo Verona");
		list.add("IF Elfsborg Borås");
		list.add("Sunderland AFC");
		list.add("Club Alianza Lima");
		list.add("Heartland FC Oweri");
		list.add("CSD Colo Colo Santiago");
		list.add("FC Zimbru Chisinau");
		list.add("Cotonsport FC de Garoua");
		list.add("PFC Neftchi Baku");
		list.add("CSCD Universidad César Valleja Trujillo");
		list.add("FC de Toulouse");
		list.add("West Bromwich Albion FC");
		list.add("Central Coast Mariners FC Gosford");
		list.add("Club Atlético Osasuna");
		list.add("Catania Calcio");
		list.add("FK Skonto R?ga");
		list.add("FC Spartak Moscow");
		list.add("Stade Malien de Bamako");
		list.add("Slaven Belupo Koprivnica");
		list.add("FK Austria Wien");
		list.add("M?K Zilina");
		list.add("NK Olimpija Ljubljana");
		list.add("Servette FC Geneve");
		list.add("Universitario de Deportes Lima");
		list.add("CD Itagüí Ditaires");
		list.add("CA Rafaela");
		list.add("FC Sion");
		list.add("FC Spartak Trnava");
		list.add("Al-Sadd SC Doha");
		list.add("CA San Lorenzo de Almagro Buenos Aires");
		list.add("Atlético Clube Goianiense Goiânia");
		list.add("UNAM Ciudad de Mexico");
		list.add("Al-Shorta SC Damascus");
		list.add("Dundee United FC");
		list.add("Enyimba International FC Aba");
		list.add("Boyacá Chicó FC");
		list.add("Brisbane Roar FC");
		list.add("VMFD Zalgiris Vilnius");
		list.add("Feyenoord Rotterdam");
		list.add("FK Zestafoni");
		list.add("FK Mladá Boleslav");
		list.add("Club Tijuana");
		list.add("CD Olimpia Tegucigalpa");
		list.add("Kitchee SC");
		list.add("Deportivo Sport Huancayo");
		list.add("FK S?duva Marijampole");
		list.add("Atalanta Bergamasca Calcio");
		list.add("SV Ried");
		list.add("AC Fiorentina Firenze");
		list.add("RCD Espanyol Barcelona");
		list.add("Figueirense FC Florianópolis");
		list.add("Sevilla FC");
		list.add("SK Rapid Wien");
		list.add("AC Mineros de Guayana Puerto Ordaz");
		list.add("PFC Ludogorets Razgard");
		list.add("FC Flora Tallínn");
		list.add("Al-Faysali Club Amman");
		list.add("CD O'Higgins Rancagua");
		list.add("TP Mazembe Lubumbashi");
		list.add("CD Unión Comercio");
		list.add("Shirak FC Gyumri");
		list.add("SK Skënderbeu Korçë");
		list.add("Motherwell FC");
		list.add("Persepolis FC Tehran");
		list.add("Club Deportivo Cuenca");
		list.add("CD La Equidad Bogotá");
		list.add("CD Universidad San Martín de Porres");
		list.add("NK Osijek");
		list.add("Real Sociedad de Futbol San Sebastián");
		list.add("Swansea City FC");
		list.add("Grupo Desportivo e Recreativo do Libolo");
		list.add("KS Ruch Chorzów");
		list.add("CD Once Caldas Manizales");
		list.add("Sivas Spor Kalübü (Sivasspor)");
		list.add("JK Nõmme Kalju");
		list.add("CD Aurora Cochabamba");
		list.add("Bany Yas SCC");
		list.add("ASEC Mimosas Abidjan");
		list.add("AC Léopard Dolisie [Congo]");
		list.add("Gyeong Nam FC Changwon");
		list.add("Club Sol de America Asunción");
		list.add("Asociación Deportivo Cali");
		list.add("Home United FC");
		list.add("Hibernian FC Edinburgh");
		list.add("Club Inti Gas Deportes Ayacucho");
		list.add("Real Garcilaso");
		list.add("FK Senica");
		list.add("Cruzeiro EC Belo Horizonte");
		list.add("Jeju United FC");
		list.add("Tampines Rovers FC");
		list.add("Al-Safa SC Beirut");
		list.add("Getafe FC");
		list.add("Al-Wehdat Club Amman");
		list.add("?K Slovan Bratislava");
		list.add("Étoile Sportive du Sahel");
		list.add("Vegalta Sendai");
		list.add("Aberdeen FC");
		list.add("Evian Thonon Gaillard FC");
		list.add("F91 Dudelange");
		list.add("Real Estelí FC");
		list.add("FC Midtjylland");
		list.add("AEK Athens");
		list.add("Manta FC");
		list.add("Houston Dynamo");
		list.add("AFA Djekanou");
		list.add("Urawa FC Red Diamonds");
		list.add("Toronto FC (Canada)");
		list.add("Éntente Sportife de Sétif");
		list.add("OGC Nice");
		list.add("AS de Nancy-Lorraine");
		list.add("TSG Hoffenheim");
		list.add("Sporting Kansas City Wizards");
		list.add("Pachuca CF");
		list.add("Sanfrecce Hiroshima FC");
		list.add("Heracles Almelo");
		list.add("RAEC Mons");
		list.add("Nasaf Qarshi FC");
		list.add("FC Platinum Zvishavane");
		list.add("NK Hajduk Split");
		list.add("CD Oriente Petrolero Santa Cruz");
		list.add("US Citta di Palermo");
		list.add("Omonia FC Lefkosia");
		list.add("CSD Comunicaciones Guatemala City");
		list.add("MyPa Anjalankoski");
		list.add("FH Hafnafjör?ur");
		list.add("CA San Martin Tucuman");
		list.add("Grenada CF");
		list.add("Bnei Yehuda FC Tel-Aviv");
		list.add("Real Zaragoza CD");
		list.add("ND Mura 05");
		list.add("Independiente José Terán del Valle");
		list.add("Stade Brest");
		list.add("Karabükspor");
		list.add("FK Sarajevo");
		list.add("Lierse SK");
		list.add("FC Milsami Orhei");
		list.add("FK Vadar Skopje");
		list.add("AEK Larnaka");
		list.add("CF América Ciudad de México");
		list.add("Power Dynamos FC Kitwe");
		list.add("CS Panduri Târgu Jiu");
		list.add("FC Zürich");
		list.add("PBS Kuala Terengganu FA");
		list.add("Sligo Rovers FC");
		list.add("Shimizu FC S-Pulse");
		list.add("Real Betis Balompié");
		list.add("Norwich City FC");
		list.add("FC Daugava Daugavpils");
		list.add("CS Gaz Methan Media?");
		list.add("Cliftonville FC Belfast");
		list.add("FC Genoa 1893");
		list.add("FC Torpedo Kutaisi");
		list.add("Al-Ahli Shandi");
		list.add("FC Yokohama F. Marinos");
		list.add("CD Lara Barquisimento");
		list.add("Sønderjysk Elitesport");
		list.add("Valletta FC");
		list.add("FC O?elul Gala?i");
		list.add("Crusaders FC");
		list.add("PFK Levski Sofia");
		list.add("Associação Academica de Coimbra");
		list.add("SC Freiburg");
		list.add("CD Saprissa San Juan de Tibás San José");
		list.add("Asociacion Deportiva Rayo Vallecano");
		list.add("Wigan Athletic FC");
		list.add("Churchill Brothers SC Goa");
		list.add("Mariano Melgar FBC Arequipa");
		list.add("Kazma SC Kuwait-City");
		list.add("FK Baumit Jablonec");
		list.add("Al-Muharraq Manama");
		list.add("OF Iraklion");
		list.add("SK Admira Wacker Mödling");
		list.add("COD Meknés");
		list.add("Kano Pillars FC");
		list.add("ENPPI Cairo");
		list.add("FC Shakhtyor Salihorsk");
		list.add("Al-Gharrafa SC Doha");
		list.add("CD Marathón San Pedro Sula");
		
		return list;
	}
}
